### ISSUE TITLE
Build error for python-pygobject

### ISSUE THREAD

**Issue by apnavik** [meta-gir/meta-gir#7]
Hi,

I have added meta-gir/meta-gir in bblayer.conf
and tried to build **girepository** using **bitbake libgirepository** but it is 
throwing error due to **g-ir-scanner.py bad interpreter: No such file or directory**

I have tested on Yocto jetro 2.0 branch. will it only work with QEMU??
Is it a know issue?? or any other configuration required ??

Please let me know answer

**Comment by locust2001** [comment]
i'll test it in jethro branch laster. Thanks for your report.

**Comment by 4urele** [comment]
Hi,

just leaved an issue... I had the same issue it seems to be related to the length of the "hash-bang" ("#!/bin/...etc), if it exceeds 128 bytes it cannot be launched. So to get it work you just have to build it again in a new directory with shorter absolute path...

Aurele
